esphome:
  name: esp32-multiboard
  friendly_name: ESP32 MultiBoard
  name_add_mac_suffix: true
  project:
    name: "thebeaverdam.esp32-multiboard"
    version: "1.0.0"

esp32:
  board: esp32dev
  
  framework:
    type: esp-idf

# Logs 
logger:

mdns:

esp32_improv:
  authorizer: none

# HA direct comunication
api:
  

# OTA
ota:
  platform: esphome
  

# WiFi: starts in AP mode + Captive Portal 
wifi:
  ap:
    ssid: "Setup_${device_name}"

    
dashboard_import:
  package_import_url: github://thebeaverdam/ESP32_MultiBoard/firmware/ESPHome.yaml

captive_portal:

 



